// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe2Do_mDfmrVjW6WgjiOHenLZxLuLdteI',
    appId: '1:126109015359:web:b6ae21ea383924a88cc78a',
    messagingSenderId: '126109015359',
    projectId: 'pueblo-entrega-app-dev-f1f94',
    authDomain: 'pueblo-entrega-app-dev-f1f94.firebaseapp.com',
    storageBucket: 'pueblo-entrega-app-dev-f1f94.firebasestorage.app',
    measurementId: 'G-B4C9TMPX5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9m8O-vdQnWGmW7f2iyao4Wl-9dUYsdRc',
    appId: '1:126109015359:android:6fa10841c1149bb98cc78a',
    messagingSenderId: '126109015359',
    projectId: 'pueblo-entrega-app-dev-f1f94',
    storageBucket: 'pueblo-entrega-app-dev-f1f94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3B0HJABUj7UVQRaGg0-CBmeQRtg8qAqA',
    appId: '1:126109015359:ios:68eaaa81a1acce798cc78a',
    messagingSenderId: '126109015359',
    projectId: 'pueblo-entrega-app-dev-f1f94',
    storageBucket: 'pueblo-entrega-app-dev-f1f94.firebasestorage.app',
    iosBundleId: 'com.example.puebloEntregaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3B0HJABUj7UVQRaGg0-CBmeQRtg8qAqA',
    appId: '1:126109015359:ios:68eaaa81a1acce798cc78a',
    messagingSenderId: '126109015359',
    projectId: 'pueblo-entrega-app-dev-f1f94',
    storageBucket: 'pueblo-entrega-app-dev-f1f94.firebasestorage.app',
    iosBundleId: 'com.example.puebloEntregaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe2Do_mDfmrVjW6WgjiOHenLZxLuLdteI',
    appId: '1:126109015359:web:a442c8ac02ed23928cc78a',
    messagingSenderId: '126109015359',
    projectId: 'pueblo-entrega-app-dev-f1f94',
    authDomain: 'pueblo-entrega-app-dev-f1f94.firebaseapp.com',
    storageBucket: 'pueblo-entrega-app-dev-f1f94.firebasestorage.app',
    measurementId: 'G-KL0PYLZLM1',
  );

}